### ISSUE TITLE
"mississippi" gives  "issi" instead of "ssi" as longest repeated substring

### ISSUE THREAD

**Issue by graste** [shrink0r/suffix-tree#4]
Expected `ssi` instead of `issi` for input `mississippi`.

![mississippi](https://cloud.githubusercontent.com/assets/203540/19215196/81575f88-8d97-11e6-93a7-09625b9828f1.png)

**Comment by shrink0r** [comment]
Isn't "issi" actually the longest repeated substring?
It is in there twice, as is "iss", but because "issi" is longer it wins.

**Comment by graste** [comment]
I'd say "ississi" doesn't contain "issi" twice.

**Comment by shrink0r** [comment]
The way it is implemented at the moment, just gives the longest repeated substring path of thedeepest internal node. This may lead to an overlapping result.
Can be seen here for the "mississippi" example:
http://www.allisons.org/ll/AlgDS/Tree/Suffix/ (see the section "Longest Repeated Substring")
Not being able to determine the non-overlapping repeated-substring can be considered a bug, because the method name is kinda ambigious concerning the result.
@graste  Do you think either a second method or an additional param '$overlap = false' make sense (1aa8b937d9caaae99ef30a3446ee4b8e17fec9ac)?

**Comment by graste** [comment]
My expectation obviously was "no overlapping" as there are not "enough" characters to actually write down the repeated substrings. That's why I'd prefer a default of `allow_overlapping = false``. As this is a library l'd prefer two methods (and maybe a private one with the boolean flag to not repeat yourself). Not sure about naming though. :-D

**Comment by MrHash** [comment]
Wouldn't 'iss' be the longest repeated substring matched ahead of 'ssi' in a non-overlapping context?

**Comment by shrink0r** [comment]
@MrHash: yes, as the substrings are built from prefixes of each suffix (l2r), "iss" will win over "ssi".
